package:
  name: bcbio-gff
  version: "0.6.4"

source:
  fn: bcbio-gff-0.6.4.tar.gz
  url: https://pypi.python.org/packages/94/df/e2d75cc688ac6eb53f5fb4e2cffd240596bbcd5be28bab8d4f6404a6f86c/bcbio-gff-0.6.4.tar.gz
  md5: 26910c9f6317b47a9e09742ecf74ae62

build:
  number: 0

requirements:
  build:
    - python
    - setuptools
    - six

  run:
    - python
    - six

test:
  # Python imports
  imports:
    - BCBio
    - BCBio.GFF

about:
  home: https://github.com/chapmanb/bcbb/tree/master/gff
  license: Bipython Licence
  summary: 'Read and write Generic Feature Format (GFF) with Biopython integration.'
  license_family: OTHER
